#!/bin/sh /etc/rc.common

#Deamon entry for weather-service, belongs in init.d/

START=90

USE_PROCD=1


start_service() {
        procd_open_instance
        procd_set_param command python3 /root/wthr-pstr/weather.py
        #procd_append_param command 0     # optionally append command parameters - this program takes the GPIO number as an argument
        procd_set_param respawn  # respawn the service if it exits
        procd_set_param stdout 1 # forward stdout of the command to logd
        procd_set_param stderr 1 # same for stderr
        procd_close_instance
}
